# Generated by Django 5.2.3 on 2025-07-25 09:54

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('extreme', 'Extreme'), ('creative', 'Creative'), ('social', 'Social'), ('adventure', 'Adventure')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DifficultyLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('extreme', 'Extreme')], max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#6B7280', max_length=7)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Dareora', max_length=100)),
                ('site_tagline', models.CharField(default='Dive into the art of daring', max_length=200)),
                ('site_description', models.TextField(default='Where innovative social technology meets thrilling experiences')),
                ('allow_submissions', models.BooleanField(default=True)),
                ('require_approval', models.BooleanField(default=True)),
                ('enable_likes', models.BooleanField(default=True)),
                ('enable_completions', models.BooleanField(default=True)),
                ('max_dares_per_user', models.PositiveIntegerField(default=5)),
                ('featured_dares_count', models.PositiveIntegerField(default=6)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
        migrations.CreateModel(
            name='Dare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Give your dare a catchy title', max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('name', models.CharField(help_text='Your full name', max_length=100)),
                ('email', models.EmailField(help_text='Your email address', max_length=254)),
                ('phone_number', models.CharField(help_text='Your phone number for verification', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('college', models.CharField(help_text='Your college/university name', max_length=200)),
                ('dare_text', models.TextField(help_text='Describe the dare in detail')),
                ('estimated_time', models.PositiveIntegerField(blank=True, help_text='Estimated time to complete (in minutes)', null=True)),
                ('required_items', models.TextField(blank=True, help_text='List any items/materials needed (optional)')),
                ('safety_notes', models.TextField(blank=True, help_text='Any safety precautions or warnings (optional)')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('featured', 'Featured')], default='pending', max_length=20)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('rejection_reason', models.TextField(blank=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('completions_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(help_text='Select the appropriate category', on_delete=django.db.models.deletion.CASCADE, related_name='dares', to='dares.category')),
                ('difficulty', models.ForeignKey(help_text='How difficult is this dare?', on_delete=django.db.models.deletion.CASCADE, related_name='dares', to='dares.difficultylevel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DareCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completer_name', models.CharField(max_length=100)),
                ('completer_email', models.EmailField(max_length=254)),
                ('completion_proof', models.TextField(help_text='Describe how you completed the dare')),
                ('completion_image', models.URLField(blank=True, help_text='Link to image/video proof (optional)')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('dare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='dares.dare')),
            ],
            options={
                'ordering': ['-completed_at'],
                'unique_together': {('dare', 'completer_email')},
            },
        ),
        migrations.CreateModel(
            name='DareLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_likes', to='dares.dare')),
            ],
            options={
                'unique_together': {('dare', 'user_email')},
            },
        ),
        migrations.AddIndex(
            model_name='dare',
            index=models.Index(fields=['status', 'is_approved'], name='dares_dare_status_5e1253_idx'),
        ),
        migrations.AddIndex(
            model_name='dare',
            index=models.Index(fields=['category', 'difficulty'], name='dares_dare_categor_743875_idx'),
        ),
        migrations.AddIndex(
            model_name='dare',
            index=models.Index(fields=['-created_at'], name='dares_dare_created_1a1c1e_idx'),
        ),
    ]
